MAIN_CONTACT_NUMBER = ""

# Secret key for signing cookies
# SECRET_KEY = "high-mont-secret-are-ksajbdakbf" #Present by Default

# Generated by Python OS Package (36 bits)
SECRET_KEY = "5d\x8b\xb3o\x1ez\x88\r,s\xe7\x10\xf7H\x89!\xaa\x9b\xffNZI\xbf\x16\x1a\x00\xaf\xd0\xb5`\x19E\xf3\xdf\x8d"
